baseURL = 'https://srix55.github.io/sumadhwa-vijaya/'
languageCode = 'en-us'
title = 'सुमध्वविजयः'
theme = 'hugo-book'
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
enableGitInfo = true    
    
[params]
  BookSection = 'docs'
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'
  BookSearch = false
  BookDateFormat = 'Jan 2, 2006'
  BookComments = false  
